apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-provider
spec:
  provider: aws   
  secretObjects:
  - secretName: application-secret
    type: Opaque
    data:
    {{- range .Values.secret_env }}
    - objectName: {{ .aws_secret }}
      key: {{ .aws_secret }}
    {{- end }}
  parameters:
    objects: |
      {{- range .Values.secret_env }}
        - objectName: {{ .aws_secret }}  # the AWS secret
          objectType: "secretsmanager"
      {{- end }}
  controllerPublishSecretRef:
    name: application-secret