name: EKS Deployment

on:
 push:
    branches:
      - main
jobs:
 build:
   runs-on: ubuntu-latest
   name: to deploy EKS application
   
   steps:
      
    - name: checkout
      uses: actions/checkout@v1

      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          
    - name: Update kubeconfig file
      run: aws eks update-kubeconfig --region $CLUSTER_REGION  --name $CLUSTER_NAME
         
    - name:  check kubectl
      run: kubectl get pods -n $NAMESPACE

    - name: Helm Upgrade
      run: helm upgrade -i $EKS_APP_NAME $HELMFOLDER_PATH -n $NAMESPACE